baseURL: "https://abhinine4.github.io"
languageCode: "en-us"
title: "Abhishek"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"
    #darkmode:
        #secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "(Updated on: 26/07/2024) Hi there! I'm "
    title: "Abhishek Kumar"
    subtitle: "Are you looking for a creative and focused person that loves to take initiative? Look no further"
    content: "I am a Machine Learning Engineer with a strong background in Computer Science and Artificial Intelligence. I am proficient in developing and implementing deep learning algorithms for a variety of applications, including text and image classification, object detection, image segmentation, and generation using diffusion and generative models."
    image: "/images/IMG_1202.jpeg"
    button:
      background - color: 
      enable: true
      name: "Resume"
      url: "https://github.com/abhinine4/resume/blob/main/Abhishek_Kumar_Resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/abhinine4
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/akumar58
        # - icon: fab fa-twitter
        #   url: https://x.com/abhisheknine4?s=21&t=os1o0Mn6cMj4MsjwS_19Iw
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work from September 2023"
    image: "/images/IMG_0521.JPG"
    content: |-
      I am a Senior Data Scientist with 4.5 years of experience in machine learning, data science, and software engineering with a
      Master’s degree in Computer Science & Engineering specializing in artificial intelligence (computer vision and NLP). I build most
      frequently with Python, C++, and PyTorch. I am currently building a conversational chatbot using generative AI that provides
      transactional insights and personalized financial advisory based on users’ spending and earning patterns. I am seeking new roles
      as an applied scientist to leverage my expertise in solving complex real-world problems
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python" 
        - "C++"
        - "Pytorch"
        - "NumPy"
        - "OpenCV"
        - "Langchain"
        - "AWS"
        - "Docker"
        - "Git"
        - "Linux"
       
  # Experience
  experience:
    enable: true 
    items: 
      - job: "Senior Data Scientist"
        company: "Mobikwik"
        companyUrl: "https://www.mobikwik.com/"
        date: "Feb 2024 - Present"
        info:
          enable: true
          content: "Location: Gurgaon, HR"
        featuredLink:
          enable: false
          url: "https://www.mobikwik.com/"
        info:
          content:
        content: |-
          Gurgaon, Haryana
          - Developed a financial advisory chatbot based on user transactional patterns using Langchain, MongoDB, Django, and LLMs. 
          - Created a multiclass scope checker module that classifies questions and provides standard responses for out-of-scope questions.
          - Developed a RAG pipeline with a question2mongo query generation module that prompts LLM models with extracted information from question and parameter mappings to generate mongo query required to retrieve custom user data.
          - Utilized Weaviate DB as a caching system to cache templated queries and metadata to lower system latency and reduce API cost.
          - Added few shot prompting and user-level feedback to improve query generation accuracy.
          - Designed a text manipulator system that takes in users' transactional categories, subcategories, banks, payment modes, and merchants to create similar follow-up questions for user engagement.
          - Built a state machine system that routes user questions to different modules based on question intent and conversation context.
          - Integrated Grafana, New Relic, and Prometheus for logging and monitoring API requests and responses.

      - job: "Computer Vision Researcher"
        company: "A2IL (now IAD)"
        companyUrl: "https://www.buffalo.edu/ai-data-science.html"
        date: "Sept 2022 - Feb 2024"
        info:
          enable: true
          content: "Location: Buffalo, NY"
        featuredLink:
          enable: false
          url: "https://www.buffalo.edu/ai-data-science.html"
        info:
          content:
        content: |-
          Buffalo, New York
          - Created a text+pose guided image generation system using latent diffusion models (ControlNet with Stable diffusion weights). 
          - Added noise and performed latent interpolation on best pair human face images to generate high-resolution morphs.
          - Generated images at different noise levels and selected the best candidate by computing CLIP similarity scores for fixed prompts.
          - Developed an image manipulation detection system to detect, localize, and label tampered parts in news articles. \hyperlink{https://github.com/abhinine4/news_forensics/blob/main/Kumar\%2CAbhishek.pdf}{Thesis}
          - Trained a CNN model with a Resnet-50 backbone to detect jpeg compression errors in tampered images with 93\% accuracy.
          - Utilized NEDB-Net to extract noise and edge-based features to localize and get manipulation mask for the tampered regions.
          - Fine-tuned a custom Yolo-v8 model to detect objects in the localized regions and classify them into 18 categories.
          - Created analytic containers to detect image text inconsistencies in multimodal news articles.
          - Developed a text-transformer tool to perform controlled named entity and parts of speech replacements in texts using SpaCy.
          - Extracted text from images using Paddle OCR and developed contradiction and mismatch detection algorithms to detect inconsistencies between image text and news body.

      - job: "Teaching Assitant - CSE 701/702"
        company: "University At Buffalo"
        companyUrl: "https://www.buffalo.edu/"
        date: "June 2022 - Aug 2022"
        info:
          enable: true
          content: "Location: Buffalo, NY"
        featuredLink:
          enable: false
          url: "https://www.buffalo.edu/"
        info:
          content:
        content: |-
          Buffalo, New York
          - Guided students to develop deep learning projects for video analysis in sports domain for CSE 701/702.
          - Conducted classes, graded assignments, and reviewed students technical presentations.

      - job: "Systems Engineer"
        company: "Infosys"
        companyUrl: "https://www.infosys.com/"
        date: "Feb 2018 - Aug 2020"
        info:
          enable: true
          content: "Location: Bhubaneswar, India"
        featuredLink:
          enable: false
          url: "https://www.infosys.com/"
        info:
          content:
        content: |-
          Bhubaneswar, India
          - Trained random forest model to classify dependent and independent parts for refrigeration systems with 97\% accuracy.
          - Developed a module to predict part prices using XGBoost regressor and integrated with CUMMINS part pricing system.
          - Built API service using Django REST Framework to parse delegation data from files received in hourly batches.
          - Developed employee task delegation system to manage production workflows and approvals using python.
          - Reduced batch data transfer failure rate by 20\% through automation and monitoring of batch jobs using RPA and Appworx.
          - Managed deployment and maintenance pipelines for system availability and reliability using Jenkins and Git/Github.   
          
      # - job: "IoT Intern"
      #   company: " BITS Pilani Indibots "
      #   companyUrl: "https://www.f6s.com/indibots"
      #   date: "June 2018 - July 2018"
      #   info:
      #     enable: true
      #     content: "Location: Hyderabad, India "
      #   featuredLink:
      #     enable: false
      #     url: "https://www.kitolit.com"
      #   content: |-
      #     Hyderabad, India
      #     - Worked on Developing a Smart Medicine reminder kit and Collaborated with other interns to define the features of the Device.
      #     - Designed the Circuit Diagram.
      #     - Presented Demo's to several Professors.


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Masters in Computer Science (Machine Learning and Computer Vision)"
        school:
          name: "University at Buffalo, New York"
          url: "https://www.buffalo.edu/"
        date: "2021 - 2023"
        GPA: "3.72 out of 4.0"
        content: |-
            - Worked as a Computer Vision Research Assistant in the IAD lab under Dr.David Doermann.
            - Built analytic components for SemaFor (DARPA) as part of the UB-SRI team.
            - Researched and wrote my thesis on : Forensic Systems to Detected Manipulated News Media.
            - Was a Teaching Assistant for graduate level courses (CSE 701/702), sports video analytics at University at Buffalo.
            - Guided students to develop deep learning projects for video analysis.
            - Courses : Deep Learing, Computer Vision and Image Processing, Machine Learning, Information Retrieval, Neurosymbolic AI (seminar), Distributed Systems, Analysis and Design of Algorithms.
            
            
            Extracurricular Activities
             - Ranked 3rd in UB Hack (org. by MLH) for our Decentralized News Platform 
             - Ranked 7th in Soccernet 2022 competition for our work on soccer player re-identification in broadcast videos.
             - Ranked 5th in Soccernet 2024 for our work on soccer Temporal Action Spotting.

      - title: "Bachelor of Technology in Mechanical Engineering"
        school:
          name: "SRM University, Chennai"
          url: "https://www.srmist.edu.in/"
        date: "2013 - 2017"
        GPA: "3.94 out of 4"
        content: |- 
          - Researched on carbon nano-tube infused phase change materials to create efficient cooling fluids.
          - Relevant Courses: Robotics, Probability and Statistics, Linear Algebra, Numerical Methods, Matlab, Advanced Calculus.
          
          Extracurricular Activities
            - Won 2nd Prize in the annual tech fest (Aaruush'14) for our Infrared based line follower robot.
            - Active member of the photography club.
          
            

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  # achievements:
  #   enable: true
  #   items:
  #     - title: Creative Collision Challenge 2022
  #       content: Won 1st Place at the University of Rochester AIN Entrepreneurship cell's yearly pitching competition.
  #     - title: Women Entrepreneurship Week Candidate 2020
  #       content: Was selected to meet a Senior Director from Jio Industries for a discussion about the Smart Yoga Instructor application AIC Incubation Center at IIIT Kottayam.
  #     - title: Elected Cultural Secretary 2019 - 2021
  #       content: Conducted 15+ events with a footprint of more than 300+ students and Managed a team of 25 students for fundraising and event organization # Conducted events virtually during COVID for effective engagement among new students.
  #       url: "https://www.iiitkottayam.ac.in/#!/culturalClub"
  #     - title: Presented my paper at ACM/CSI/IEEE-CS Conference. 
  #       content: Author of “IoT based Smart Medicine Reminder Kit” at ACM/CSI/IEEE-CS Research and Industry Symposium at IIIT Kottayam (My Bachelor's Honors Project)

  # projects
  projects:
    enable: true
    items:
      - title: Temporal Action Spotting
        content: Implemented a transformer based model with multiscale flow and RGB features to classify actions and identify temporal boundaries for 17 action classes. Achieved 52 % mAP and ranked 5th in Soccernet competition. 
        image: /images/projects/action.png
        featured:
          name: Click here to know more!
          link: https://www.soccer-net.org/tasks/action-spotting
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/abhinine4/Action_Spotting/tree/main/SoccerNet-Action-Spotting/actionformer_release
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Text-to-Image using Residual GANs
        content: Developed a Deep Residual GAN network to create images from latent noise. Used BIRD CUB-200 dataset to train the model. 
        image: /images/projects/bird.png
        featured:
          name: Click here to know more!
          link: https://github.com/abhinine4/TextToimage_Residual_GANs/blob/main/Final_Report_CSE676.pdf
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/abhinine4/TextToimage_Residual_GANs

      - title: Image Denoiser
        content: Developed a CNN model in PyTorch that uses residual learning on deep CNNs to remove noise from iamges.
        image: /images/projects/denoise.png
        featured:
          name: Click here to know more!
          link: https://github.com/abhinine4/image_denoiser
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/abhinine4/image_denoiser
      
      - title: Player Re-Identification
        content: Designed a dual branch deep learning model to re-identify soccer players across multiple camera viewpoints depicting the same action during the game. Fused appearence and body part features from a subnet of OpenPose using Compact bilinear pooling to get the fused features. 
        image: /images/projects/reid.png
        featured:
          name: Click here to know more!
          link: https://github.com/abhinine4/Soccerplayer_Reidentification/blob/main/images/soccer_player_reid_report.pdf
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/abhinine4/Soccerplayer_Reidentification

      - title: Splice Detector
        content: A Deep Convolutional Neural Network model to detect manipulated images using JPEG compression analysis. 
        image: /images/projects/splice.png
        featured:
          name: Click here to know more!
          link: https://github.com/abhinine4/Image_splice_detection
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/abhinine4/Image_splice_detection

  #Contact
  contact:
    enable: true
    content: Drop an email for any questions. My inbox is always open !
    email: akumar58@buffalo.edu
    btnName: Email

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/abhinine4
      linkedin: https://www.linkedin.com/in/akumar58
      # twitter: https://x.com/abhisheknine4?s=21&t=os1o0Mn6cMj4MsjwS_19Iw
      # instagram: https://www.instagram.com/keerthi__sreenivas/
    # facebook: https://facebook.com
